/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rameshdhanekula' at '9/6/17 5:22 PM' with Gradle 3.0
 *
 * @author rameshdhanekula, @date 9/6/17 5:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
